FROM ubuntu:latest
RUN apt update -y  && apt upgrade -y 

WORKDIR /flask_tutorial

COPY . .

ADD [--chown=<user>:<group>] <src>... <dest>
ADD [--chown=<user>:<group>] ["<src>",... "<dest>"]

RUN yarn install --production

EXPOSE 5000:80/udp
EXPOSE 5000:80/tcp

ENV myenv="placeholder"

CMD ["flask run", "src/index.js"]