FROM ubuntu:latest
RUN apt update -y  && apt upgrade -y 
RUN mkdir flask_tutorial

#VOLUME /flask_tutorial/
WORKDIR /flask_tutorial/


#add can use urls
ADD https://github.com/PandaJoey/flask-cicd-first-try /flask_tutoial/

RUN cd flask_tutoial/
RUN apt install python3.9-venv
RUN apt install python3-flask
RUN pip install Flask
RUN python3 -m venv venv
RUN . venv/bin/activate
RUN export FLASK_APP=flaskr
RUN export FLASK_ENV=development
RUN flask init-db


EXPOSE 5000:80/udp
EXPOSE 5000:80/tcp

ENV myenv="placeholder"

#exec
ENTRYPOINT ["executable", "param1", "param2"]

#shell
#ENTRYPOINT command param1 param2
CMD ["flask run", "/flask_tutoial"]