FROM ubuntu:latest
RUN apt update -y  && apt upgrade -y 

WORKDIR /flask_tutorial/

#add can use urls
ADD https://github.com/PandaJoey/flask-cicd-first-try /flask_tutoial/

RUN yarn install --production

EXPOSE 5000:80/udp
EXPOSE 5000:80/tcp

ENV myenv="placeholder"

ENTRYPOINT command param1 param2
CMD ["flask run", "src/index.js"]