FROM ubuntu:latest
RUN apt-get update -y  && apt-get upgrade -y --no-install-recommends
RUN apt-get install git -y --no-install-recommends
RUN apt-get install apt-utils -y --no-install-recommends
RUN mkdir flask_tutorial

#VOLUME /flask_tutorial/
RUN pwd
RUN pwd
RUN pwd
RUN pwd

COPY . .
#add can use urls
#RUN git clone https://github.com/PandaJoey/flask-cicd-first-try.git
RUN cd /flask_tutorial/
RUN pwd
RUN pwd
RUN pwd
RUN pwd

#RUN apt-get install python3.9-venv -y --no-install-recommends
RUN apt-get install python3.8-venv -y --no-install-recommends
RUN apt-get install python3-flask -y --no-install-recommends
RUN apt-get install pip -y --no-install-recommends
RUN pip install Flask
RUN python3 -m venv venv
RUN . venv/bin/activate
RUN export FLASK_APP=flaskr
RUN export FLASK_ENV=development
RUN flask run


EXPOSE 5000/udp
EXPOSE 5000/tcp

ENV myenv="placeholder"

#exec
#ENTRYPOINT ["executable", "param1", "param2"]

#shell
#ENTRYPOINT command param1 param2
CMD ["flask run", "/flask_tutorial"]