FROM ubuntu:latest
RUN apt-get update -y  && apt-get upgrade -y --no-install-recommends
RUN apt-get install git -y --no-install-recommends
RUN apt-get install apt-utils -y --no-install-recommends
RUN apt-get install python3.8-venv -y --no-install-recommends
RUN apt-get install python3-flask -y --no-install-recommends
RUN apt-get install pip -y --no-install-recommends
RUN pip install Flask
#VOLUME /flask_tutorial/

ADD ./* /flask_tutorial/
#add can use urls
#RUN git clone https://github.com/PandaJoey/flask-cicd-first-try.git

#RUN apt-get install python3.9-venv -y --no-install-recommends
WORKDIR /flask_tutorial

ENV FLASH_APP=flaskr
ENV FLASK_ENV=development
RUN flask run


EXPOSE 5000/udp
EXPOSE 5000/tcp

#exec
#ENTRYPOINT ["flask", "run"]

#shell
#ENTRYPOINT command param1 param2
#CMD ["flask run", "/flask_tutorial"]